name: Website To HTML

on:
  workflow_dispatch:
    inputs:
      website:
        description: "Website URL"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Install Node
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install SingleFile
      run: npm install -g single-file-cli

    - name: Download Website
      run: |
        single-file "${{ github.event.inputs.website }}" output/download.html

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: downloaded-html
        path: output/download.html
