name: Website To HTML

on:
  workflow_dispatch:
    inputs:
      website:
        description: "Website URL"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Create Output Folder
      run: mkdir -p output

    - name: Download Website
      run: |
        wget -E -H -k -K -p "${{ github.event.inputs.website }}" -P output

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: downloaded-html
        path: output
